-- 코드를 입력하세요
With CARS AS (
    SELECT CAR_ID, R.CAR_TYPE, DISCOUNT_RATE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    LEFT JOIN CAR_RENTAL_COMPANY_CAR R
    ON D.CAR_TYPE = R.CAR_TYPE
    WHERE 1=1
    AND CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS Decimal) = 30
),
RENT AS (
    SELECT *, CASE WHEN END_DATE < '2022-11-01' or START_DATE > '2022-11-30' THEN 0
            ELSE -1 END AS NOV_RENT_YN
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
NOV_RENT AS (
    SELECT CAR_ID
    FROM RENT
    GROUP BY CAR_ID
    HAVING SUM(NOV_RENT_YN) = 0
)

SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100, 0) AS FEE
FROM CARS
WHERE 1=1
AND CAR_ID IN (SELECT CAR_ID FROM NOV_RENT)
AND DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC