WITH PERC AS (
    SELECT *, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_PERC
    FROM ECOLI_DATA
)

SELECT ID,
        CASE WHEN COLONY_PERC = 1 THEN 'CRITICAL'
            WHEN COLONY_PERC = 2 THEN 'HIGH'
            WHEN COLONY_PERC = 3 THEN 'MEDIUM'
            WHEN COLONY_PERC = 4 THEN 'LOW'
        END AS COLONY_NAME
FROM PERC
ORDER BY ID

