# -- 코드를 입력하세요
# SELECT I.REST_ID, 
# I.REST_NAME, 
# I.FOOD_TYPE,
# I.FAVORITES, 
# I.ADDRESS, 
# ROUND(AVG(REVIEW_SCORE),2) AS SCORE
# FROM REST_REVIEW AS R
# LEFT JOIN REST_INFO AS I
# ON R.REST_ID = I.REST_ID
# GROUP BY REST_ID
# HAVING SUBSTR(ADDRESS, 1, 2) = '서울'
# ORDER BY SCORE DESC, FAVORITES DESC

SELECT ri.REST_ID
     , ri.REST_NAME
     , ri.FOOD_TYPE
     , ri.FAVORITES
     , ri.ADDRESS
     , COALESCE(ROUND(AVG(rr.REVIEW_SCORE),2),0) SCORE
FROM REST_INFO ri
INNER JOIN REST_REVIEW rr ON ri.REST_ID = rr.REST_ID
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY 1
ORDER BY 6 DESC, 4 DESC