-- 코드를 입력하세요
SELECT I.REST_ID, 
I.REST_NAME, 
I.FOOD_TYPE,
I.FAVORITES, 
I.ADDRESS, 
ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS R
LEFT JOIN REST_INFO AS I
ON R.REST_ID = I.REST_ID
GROUP BY REST_ID
HAVING SUBSTR(ADDRESS, 1, 2) = '서울'
ORDER BY SCORE DESC, FAVORITES DESC