-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y') as YEAR, DATE_FORMAT(SALES_DATE, '%m') AS MONTH, GENDER, COUNT(DISTINCT O.USER_ID) as USERS
FROM ONLINE_SALE O LEFT JOIN USER_INFO U
ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY DATE_FORMAT(SALES_DATE, '%Y'), DATE_FORMAT(SALES_DATE, '%m'), GENDER
ORDER BY YEAR, MONTH, GENDER
;
