-- 코드를 입력하세요
SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_INS LEFT JOIN (SELECT ANIMAL_ID, DATETIME AS OUT_DATETIME
                          FROM ANIMAL_OUTS) AS OUTS
ON ANIMAL_INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE DATETIME IS NOT NULL AND OUT_DATETIME IS NULL
ORDER BY DATETIME
LIMIT 3;