-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) AS SALES
     FROM BOOK_SALES
     WHERE MONTH(SALES_DATE)='01'
     GROUP BY BOOK_ID) AS A
     LEFT JOIN BOOK
     ON A.BOOK_ID = BOOK.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;